# Generated by Django 4.0.4 on 2022-05-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothshowroom',
            old_name='isConfirmed',
            new_name='is_confirmed',
        ),
    ]
