# Generated by Django 4.0.4 on 2022-05-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип')),
                ('address', models.CharField(blank=True, max_length=254, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=350, null=True, verbose_name='Описание')),
                ('article', models.IntegerField(unique=True, verbose_name='Артикул')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Ткань',
                'verbose_name_plural': 'Ткани',
            },
        ),
    ]
