# Generated by Django 4.0.4 on 2022-05-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='color',
            field=models.CharField(choices=[('Без принта', (('white', 'Белый'), ('black', 'Черный'), ('blue', 'Синий'), ('red', 'Красный'), ('yellow', 'Жёлтый'), ('green', 'Зелёный'), ('orange', 'Оранжевый'), ('gray', 'Серый'), ('brown', 'Коричневый'), ('cyan', 'Голубой'))), ('С принтом', (('dots', 'Горошек'), ('cell', 'Клетка'), ('graphic', 'Графический'), ('floral', 'Цветочный'), ('strip', 'Полоска'), ('cartoon', 'Мультяшный')))], default=1, max_length=25, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloth',
            name='material',
            field=models.CharField(choices=[('Текстильные', (('g1e1', 'Хлопок'), ('g1e2', 'Лён'), ('g1e3', 'Шерсть'), ('g1e4', 'Шёлк'), ('g1e5', 'Эко-кожа'))), ('Технические', (('g2e1', 'Огнестойкая'), ('g2e2', 'Для фильтрации'), ('g2e3', 'Водостойкая'), ('g2e4', 'Обтирочная'), ('g2e5', 'Изоляционная')))], default=1, max_length=25, verbose_name='Материал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloth',
            name='price',
            field=models.FloatField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='district',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default=1, max_length=25, verbose_name='Округ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloth',
            name='article',
            field=models.IntegerField(help_text='6 уникальных цифр', unique=True, verbose_name='Артикул'),
        ),
    ]
