# Generated by Django 4.0.4 on 2022-05-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0002_cloth_color_cloth_material_cloth_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='district',
            field=models.CharField(choices=[('cenral', 'Центральный'), ('northwest', 'Северо-западный'), ('ural', 'Уральский'), ('south', 'Южный'), ('privolzhsky', 'Приволжский'), ('fareastern', 'Дальневосточный'), ('siberian', 'Сибирский')], max_length=25, verbose_name='Округ'),
        ),
    ]
