# Generated by Django 4.0.4 on 2022-05-14 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloth', '0004_favourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackToCloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('text', models.CharField(max_length=300, verbose_name='Текст')),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.cloth', verbose_name='Ткань')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв к ткани',
                'verbose_name_plural': 'Отзыв к ткани',
            },
        ),
    ]
