# Generated by Django 4.0.4 on 2022-05-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0006_alter_feedbacktocloth_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='date_of_foundation',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Дата основания'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='link_to_the_catalog',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на каталог'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='link_to_the_site',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='types_of_fabrics',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Виды тканей'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Номер телефона'),
        ),
    ]
